import umap.umap_ as umap
from sentence_transformers import SentenceTransformer
import matplotlib.pyplot as plt
model = SentenceTransformer('paraphrase-multilingual-mpnet-base-v2')
model.max_seq_length = 48

sentences = [
"Staropramen 50cl",
"Falcon Export 50cl",
"Brooklyn EIPA 50cl",
"Brooklyn Lager, 50cl",
"Inget",
"Chili Cheese Burger",
"Hot Cheddar",
"Utan Salt Gurka",
"Cheddar Cheese Burger",
"Sub Oumph Caesar",
"Caesar Salad",
"Pomme frites",
"Grilled Chicken Club Sandwich",
"Pepsi 50cl",
"Vatten Gratis",
"Hot Buffalo Chicken Wings - 15 PCS",
"Blue Cheese Dressing",
"7-up 50cl",
"Bourbon BBQ Ribs",
"Brooklyn Defender 50cl",
"Lightly Salted Fries",
"Majonäs",
"Stam Öl",
"Zingo 50cl",
"Somersby Pear Cider 33cl",
"Truffle Mayo",
"Truffle Oozing Burger",
"Kronenburg 1664 Blanc 33 cl",
"Pepsi Max 50cl",
"Beef & Cheese Nachos",
"Parmesan & Garlic Sauce",
"Bacon BBQ Burger",
"Halloumi Fries",
"Carlsberg Hof 50cl",
"Öppen Bowling",
"Fish & Chips",
"Öppen Mat",
"Ramlösa 33cl",
"O'Learys BBQ Sampler",
"Shots 4cl",
"Andiamo White 18cl",
"Side Salad",
"Falcon Export 60cl",
"Garlic Bread",
"Somersby Apple Organic",
"Creamy Beef Tenderloin Pasta",
"Personalöl",
"Kampanjvin Glas",
"Chocolate Brownie",
"Pepsi 40 cl",
"Pepsi Max 40cl",
"Kids Chicken Nuggets",
"Crispy Halloumi Burger",
"Shots 6cl",
"Samuel Adams Lager",
"Sub Fries to Loaded Fries",
"Aioli",
"Giant Double Cheese Burger",
"Chili Mayo",
"Cappuccino",
"Staropramen, 50cl",
"Lagunitas IPA 35,5cl",
"Super Combo Plate",
">> Falcon Export 50cl",
"Puycherich Syrah Rose 18cl",
"Popcorn",
"Eriksberg 50cl",
"Ramlösa citrus, 33cl",
"Add Garlic Bread",
"Drink 4cl",
"Pulled Beef & Bacon Burger",
"PKT Parmesan Garlic Wings 10pcs",
"Oumph Quesadilla",
">> Brooklyn Lager, 50cl",
"Coffee",
"Salty Apple Crumble",
"Guinness 50cl",
"Stam 50cl",
"Hot Buffalo Chicken Wings - 10 PCS",
"Öppen Event",
"Mojito 4cl",
"Andiamo Red 18cl",
"Mojito 6cl",
"Carlsberg Non Alco",
"7up 50cl",
"Brooklyn Special Effects",
"Staropramen 60cl",
"Corona",
"Drink 6cl",
"Snacks",
"Med Aioli",
"Kids Cheeseburger",
"Pepsi Max 30cl",
"Red Bull",
"Cava mas pere brut 1/1",
"Kids Quesadilla",
"Juice 40cl",
"Hot Crispy Burger",
"Andiamo Rose 18cl",
"Med Guacamole",
"Medium rare",
"Classic Steak - Striploin",
"Margarita 4cl",
"Sub Fries to Sweet Potato Fries",
"Jalapeno Oumph Burger",
"Medium well",
"Medium",
"Tullamore Coffe 6cl",
"Jamaican Coffee 4cl",
"Erdinger Hefe 50cl",
"Bearnaise",
"Kaffe & Mjölk",
"Somersby Non Alco",
"Grilled Chicken Quesadillas",
"Snabbt",
"Hot Buffalo Chicken Wings - 5 PCS",
"Guacamole",
"Stam Drink 4cl",
"Aperol Spritz 6cl",
"Nachos",
"Jamaican Coffee 6cl",
"Margarita 6cl",
"Classic Steak - Tenderloin",
"BBQ Grilled Chicken",
"Redbull&Vodka 6cl",
"Cava mas pere brut, glas",
"Gnarley Chard 18cl",
"Hot Shot",
"Ice Cream Sundae",
"Stammis Shot 4cl",
"Öppet Vin",
"Espresso & Ice Cream",
"Gnarly Head Old Vine Zinfandel, 18cl",
"Tacos Del Mar",
"Gäst 1",
"Camarones Rojos Fritos",
"Plato De Carne",
"Carlsberg Alcohol Free",
"Fruta Citrica",
"Rosquilla Frita",
"Manzana Fresca",
"Brule De Crema",
"Plato De Pescado",
"Gris De Trop FL",
"Espresso Martini de laysa",
"Stam ÖL",
"Castellanovo GL",
"Coliflor Frita",
"Carbon Frito",
"Lomo Bajo (Biff)",
"Mediumrare",
"Pisco Sour de Camila",
"Morgan Bay Cab GL",
"Dubbel Espresso",
"Lagunitas IPA",
"Estrella Galicia",
"Pimientos De Padron",
"Öppen Vin",
"Brooklyn Lager",
"Nonno´s Favorito",
"Ceviche de Pescado",
"Carnitas Con Aguacate",
"Embutido Con Trufa",
"Krossad potatis",
"Bryggkaffe",
"Huber Terrassen FL",
"Maiz a la Parrilla",
"El Mariachi",
"Paso a Paso GL",
"Villa Conchi GL",
"Gäst 2",
"Öppen sprit",
"Stam DRINK",
"Pîna de Bellini",
"Bolas De Flote",
"Brooklyn Naranjito",
"Rare",
"Honoro Vera FL",
"Carlsberg Export",
"Kaffedrink",
"Alkoholfritt Vin FL",
"Vegetariano",
"Gäst 3",
"El Cubano",
"El Cerdo Maravilloso",
"Zacapa Centenario 23yo",
"Lomo Alto (Entrecote)",
"Drink 1",
"Zingo",
"Tacos Vegetariano",
"Garage Hard Lemon",
"Margarita de sangre",
"Pepsi",
"Espresso",
"Caffe Latte",
"Cours De Dame Blanc GL",
"Öppen mat",
"Te",
"Cava GL",
"Kroketter",
"Stam VIN",
"Chilibearnaise",
"Pepsi Max",
"Lander Jenkins Pinot FL",
"SLÄCK LAMPAN",
"Drink 2",
"Villa Conchi FL",
"Pina Pina Alex",
"Honoro Vera GL",
"7up",
"Well Done",
"Alkofri Drink",
"Paso A Paso Verdejo FL",
"Morgan Bay Chard GL",
"Paso a Paso FL",
"Morgan Bay Cab FL",
"Caipirinha de Pîna",
"Läsk",
"Cereza de Amor",
"Boulard Cidre De Normandie",
"Carlsberg Export 33 cl",
"Zingo 40cl",
"Jalapeno Popper - 2 PCS",
"Kids Pancakes",
"Kids Brownie",
"Kids Sundae",
"Free Popcorn",
"Alkoholfri drink",
"Tullamore Coffe",
"Parmesan Garlic Wings 15pcs",
"Med Bacon",
"Med Bearnaise",
"Andiamo Red 75cl",
"Brooklyn Lager, 40cl",
"Deep Fried Brownie",
"Add Bacon",
"Herb Butter Grilled Salmon",
"Sub Fries to Salad - Free",
"Gin´n Tonic 6cl",
"Utan lök",
"Utan BBQ",
"Utan Pommes frites",
"Med Sallad",
"Gin ´n Tonic 4cl",
"Aperol Spritz 4cl",
"Redbull&Vodka 4cl",
"The Macallan Fine Oak 12y",
"Sigtuna NAPA non alc",
"Falcon Export pitcher",
"Staropramen pitcher",
"Brooklyn Lager pitcher",
"Hernö Gin och Tonic 4cl",
"Hernö Gin och Tonic 6cl",
"Galliano Martini 6cl",
"Utan Pica De Gallo",
"Onion Ring - 2 PCS",
"Staropramen 40cl",
"Utan Gurka",
"Sweet Potato Fries",
"Pripps Blå 1",
"Öppen Läsk",
"Falcon Export 40cl",
"Cheesy Fries",
"Stam Cider",
"Mozzarella Stick - 2 PCS",
"PKT Parmesan Garlic Wings 5pcs",
"Kids Fish N'Chips",
"Mån Whisky",
"Medium Well",
"Dubble Up Your Burger",
"Add Bacon - Burger",
"Grönstedt VS CC",
"Grönstedts XO",
"Öppen Sprit",
"Personal Drink 4cl",
"Brooklyn Lager 60cl",
"Brooklyn Defender 60cl",
"Carlsberg Hof 60cl",
"Juice 50cl",
"Utan Dressing",
"Glutenfri",
"Utan Jalapenos",
">> Falcon Export 60cl",
"Carlsberg Hof 40cl",
"Öppen Öl",
"Gnarly Head Old Vine Zinfandel, 75cl",
"Boulard Grand Solage Calvados",
"Utan Lök",
"Paso A Paso Verdejo GL",
"Gris De Trop GL",
"Personal Shot",
"Jäger-Redbull Dr 4cl",
"Tacos Con Carne",
"Calamares",
"1664 Blanc",
"Caesar Cardini Ensalada",
"Carajillo Cubano",
"Cours De Dame Blanc FL",
"Lynchb.Lemonade 4cl",
"Kids Vegetables",
"San Miguel 33cl",
"Alkoholfritt Vin GL",
"Kronenbourg Blanc NAB",
"Jalapeno-Lime Mayo",
"Tea",
"Brooklyn EIPA 60cl",
"Shot 2 cl",
"Hamburgerdressing",
"2 Glas",
"Ocean Spray Cranberry",
"Utan Is",
"Med Citron",
"Mjölk",
"Utan Sallad",
"Utan Ost",
"Andiamo White 75cl",
"Sub Fried Chicken",
"Sub Salmon",
"Utan Bacon",
"Chocolate Milkshake",
"Guinness 60cl",
"Grimbergen Blonde 33cl",
"5 Glas",
"Margarita el diabolo",
"Bröd med Dip",
"Mi Abuela la Loca",
"Espresso Martini de laysa #2",
"Alex #2",
"Diplomatico Reserva",
"Societa Chianti GL",
"Somersby Pear 33cl",
"Potatispure",
"Alex #1",
"Brooklyn Summer Ale",
"Facundo Eximo",
"Barolo Ratti FL",
"Anejo Cuatro",
"Brooklyn EIPA 40cl",
"Laphroaig 10y",
"Side Caesar Salad",
"Hunky Dory Sav FL",
"Med Tomat",
"Pickled CuCumber",
"Side Tomato Salad",
"Double Espresso",
"Espresso Martini",
"Cotes De Rhone Villages FL",
"Gräddfil",
"7-up Liten",
"Carlsberg Hof pitcher",
"Galliano Martini",
"Puycherich Syrah Rose 75cl",
"Ron Zacapa Centario 23",
"Utan Champinjoner",
"Jim Beam Sour 4cl",
"El Mariachi #2",
"Tapiz Cabernet Sauvignon FL",
"Somersby Apple NAB",
"MovEat",
"Mezcalita",
"Castellanovo FL",
"Barceló Imperial Onyx",
"Gnarley Chard 75cl",
"Pepsi Maxi stor",
"Pepsi Stor GD",
"Helado",
"Pisco",
"Cidraie Original Organic 33cl",
"Brooklyn Defender 40cl",
"Parmesan & Garlic Ribs",
"Jim Beam Bourbon CC",
"Jack Daniels",
"Gentleman Jack Daniels",
"Utan Guacamole",
"Utan Bearnaise",
"Utan Aioli",
"Lomo Baja (Biff)",
"Vanilj",
"Morgan Bay Chard FL",
"Maria Bonita GL",
"Café con chocolate",
"1/2 Rött vin",
"7-up 60cl",
"Sub Fries to Caesar - Free",
"Med Jalapenos",
"Extra Cheese",
"Angostura 1919",
"Red Bull Jäger 5cl",
"Utan Cole Slaw",
"1/2 Vitt vin",
"MovEat Vegan",
"Martini Bianco",
"El Dorado 15yo",
"Long Island Iced Tea",
"Gravade Minervois 18cl",
"Side Sallad",
">> Falcon Export 40cl",
"Espresso Martini 6cl",
"Jäger-Redbull Dr 6cl",
"Knob Creek CC",
"Gäst 4",
"Daquiri de Duranzo",
"The Grinder Shiraz FL",
"Highland Park 12y",
"Barn Mjölk",
"Moscow Mule 4cl",
"Dubbel Macchiato",
"Utan Tomat",
"Patron",
"Maria Bonita FL",
"Öppen Rom",
"Brooklyn EIPA Pitcher",
"Strawberry Milkshake",
"Med Ost",
"Guinness 40cl",
"The Grinder Shiraz GL",
"Personal Cider",
"Maker's Mark",
"Personal Vitt Glas",
"Noble Vines 337 75cl",
"Ebbio Nebbiolo 75cl",
"Grönstedts Monopole VSOP",
"Ramlösa 80cl",
"Pepsi 40cl",
"Personal Rött Glas",
"Utan Grönsaker",
"Grey Goose",
"Cortado",
"Presentkort",
"Societa Chianti FL",
"Med Gurka",
"Tyris IPA",
"Amargo Dulce",
"Martell VS",
"Play off Nachos",
"7up 40cl",
"Brooklyn Defender Pitcher",
"Redan fått",
"Frozen Daiquiri 4 cl",
"Redan Fått",
"Delad",
"Andiamo Rose 75cl",
"Personal Drink 6cl",
"Bacardi Blanca",
"Med Cole Slaw",
"Jamaica Plain 5cl",
"Noble vines 242 75cl",
"Huber Terassen GL",
"Brugal 1888",
"ITA Prosecco GL"
]

# create embeddings
embeddings = model.encode(sentences)

# reduce to two dimensions
mapper = fit = umap.UMAP(n_neighbors=15, metric='cosine').fit_transform(embeddings)

# plot
x = mapper[:,0]
y = mapper[:,1]
fig, ax = plt.subplots()
fig.set_size_inches(24, 18)
ax.scatter(x, y, s=3)

# add text labels with the names to the plot
for i, txt in enumerate(sentences):
    ax.annotate(txt, (x[i], y[i]), fontsize=5)

plt.show()